name: ANTLR Grammar validator

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

jobs:
  grammar-validator:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15.0

    - name: run validate
      run: |
        cd tools
        ./validate-grammar.sh
