name: ANTLR Grammar validator

# Triggers the workflow on pull request events that update the branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  grammar-validator:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15.0

      # Install build grammar global tool
    - name: Install BuildGrammar tool
      run: |
        dotnet tool install --version 1.0.0-alpha.1 --global --add-source ./.github/workflows/dependencies/ EcmaTC49.BuildGrammar
    

    - name: run validate
      run: |
        cd tools
        ./validate-grammar.sh
