name: Markdownlint

on:
  push:
    branches:
      - draft-v6
      - draft-v7
      - draft-v8
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  pull_request:
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  lint:

    runs-on: ubuntu-latest
    permissions:
        statuses: write

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      with:
        config: ".markdownlint-cli2.jsonc"
        globs: "standard/*.md"
