name: Markdownlint

on:
  push:
    branches:
      - draft-v6
      - draft-v7
      - draft-v8
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  pull_request:
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  lint:

    runs-on: ubuntu-latest
    permissions:
        statuses: write

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
      with:
        config: ".markdownlint-cli2.jsonc"
        globs: "standard/*.md"
