name: Renumber standard TOC

# Triggers the workflow on pull request events that update the branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  renumber-sections:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    env:
      DOTNET_NOLOGO: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Run section renumbering dry run
      id: section-renumber
      run: |
        cd tools
        ./run-section-renumber.sh

    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: "dotnet",
            repo: "csharpstandard",
            workflow_id: 'report-status.yml',
            ref: '${{ github.head_ref }}',
            inputs: {
              "head_sha": '${{ steps.section-renumber.output.head_sha }}',
              "name": '${{ steps.section-renumber.output.check_name }}',
              "conclusion": '${{ steps.section-renumber.output.conclusion }}',
              "summary": '${{ steps.section-renumber.output.summary }}',
              "annotations": '${{ steps.section-renumber.output.annotations }}'
            }
          })
