name: Renumber standard TOC

# Triggers the workflow on pull request events that update the branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  renumber-sections:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    env:
      DOTNET_NOLOGO: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Run section renumbering dry run
      run: |
        cd tools
        ./run-section-renumber.sh ${{ github.event.pull_request.head.sha }}
