name: Text examples

# Triggers the workflow on pull request events that update the branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '/standard/*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  test-extraction-and-runner
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Extract and validate tests
      run: |
        cd tools
        ./test-examples.sh
