name: Test examples

# Triggers the workflow on pull request events that update the branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "standard/*.md"
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  test-extraction-and-runner:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    # We build examples against .NET 6.0, but use
    # 8.0 for the tools themselves. (The closer we
    # are to the target language version we're standardising,
    # the better.)
    - name: Setup .NET 6.0 and 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Extract and validate tests
      run: |
        cd tools
        ./test-examples.sh
