name: Update spec on merge

# Triggers the workflow on push to spec version branches.
# test-branch can be used to test this workflow.
on: 
  push:
    branches:
      - standard-v6
      - standard-v7
      - draft-v8
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  create-pull-request-for-sections-and-grammar:
    runs-on: windows-2022
    permissions:
      statuses: write
      contents: write
      pull-requests: write    
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15.0

    - name: Smarten quotes
      id: smarten-quote
      run: | 
        cd tools
        ./run-smarten.sh
      shell: bash

    - name: Renumber sections
      id: renumber-sections
      run: |
        cd tools
        ./run-section-renumber-update.sh
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.4.1
      if: ${{ steps.renumber-sections.outputs.status }} == 'success' && ${{ steps.update-grammar.outputs.status }} == 'success'
      with:
        title: "Automated Section renumber and grammar extraction"
        body: "renumber sections. Add grammar"

    - name: Run converter
      id: run-converter
      run: |
        cd tools
        ./run-converter.sh
      shell: bash

    - name: Upload Word artifact
      uses: actions/upload-artifact@v3
      if: > 
        ${{ steps.renumber-sections.outputs.status }} == 'success' && 
        ${{ steps.update-grammar.outputs.status }} == 'success' && 
        ${{ steps.run-converter.outputs.status }} == 'success'
      with:
        name: standard.docx
        path: ./tools/tmp/standard.docx
        retention-days: 15
