name: Word Converter

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

jobs:
  word-converter:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run converter
      run: |
        cd tools
        ./run-converter.sh
